#!/usr/bin/env sh
###
### Extracts whatever archive
###

# Checks
[ -z "$1" ] && echo "Usage: extract <file>.<tar.gz|zip>" && exit 0
[ ! -f "$1" ] && echo "File doesn't exist!" && exit 1

mime=$( file -i "$i" | cut -d ":" -f 2 | cut -d "/" -f 2 | cut -d ";" -f 1 )

case "$mime" in
  "gzip") tar xvzf $1  ;;
  "zip")  unzip $i     ;;
  *) printf "Not yet supported %s" "$i" ;;
esac
