#!/bin/sh

###############################################################################
# Script name	: crypt.sh 
# Author	: Valerio Casalino
# Licence	: GPLv3
# Description	: Encrypt and decrypt files in terminal
###############################################################################

msg() { echo "[+] $1"; }
err() { echo "[+] ERROR: $1" >&2; exit 1; }

usage() {
    echo "Usage: crypt [opt] <args> <input-file>\n" \
         "-d|--decrypt            : Decrypt the input file\n" \
         "-o|--outfile <filename> : Name output file\n" \
         "-h|--help               : Show this usage"
}

encrypt() {
    msg "Encrypting $1 -> $2"
    openssl enc -aes-256-cbc -salt -pbkdf2 -in "$1" -out "$2" || err "encrypt"
    exit 0
}

decrypt() {
    msg "Decrypting $1 -> $2"
    openssl enc -aes-256-cbc -d -pbkdf2 -in "$1" -out "$2" || err "decrypt"
    exit 0
}

# shellcheck disable=SC2068
are_installed() { command -v $@ > /dev/null || return 1; }

while [ $# -ne 0 ]; do case "$1" in
    -d|--decrypt) [ -z "$todecrypt" ] && todecrypt="true"; shift ;;
    -o|--outfile) shift; [ -z "$outFile" ] && outFile="$1" ;;
    -h|--help) usage && exit 0 ;;
    *) [ -f "$1" ] && inFile="$1" || err "$1 is not a regular file" ;;
esac; shift; done

are_installed openssl || err "You need openssl to run this"

[ -n "$todecrypt" ] && decrypt "$inFile" "${outFile:-${inFile%%.*}.crypt}"
encrypt "$inFile" "${outFile:-${inFile%%.*}.decrypt}"
