#!/bin/sh
# Utility to extract text from a .docx file.

err() { echo "[+] ERR: $1"; exit 1; }

[ -f "$1" ] || err "$1 is not a regular file"
command -v unzip >/dev/null || err "install unzip"

unzip -p "$1" word/document.xml \
  | sed -e 's/<\/w:p>/\n/g; s/<[^>]\{1,\}>//g; s/[^[:print:]\n]\{1,\}//g'
