#!/usr/bin/env sh

###############################################################################
# Author	: Valerio Casalino
# Description	: Clone from github with no pain 😎
###############################################################################

error() { printf "\033[31m%s\033[0m\\n" "$1"; exit 1; }

usage(){ 
  printf "Usage: %s [-h] [-t|-s] -u <username>\\n\\n" "$( basename "$0" )"
  printf "        -h|--help      Print usage\\n"
  printf "        -t|--http      Clone with https (default)\\n"
  printf "        -s|--ssh       Clone with ssh\\n"
  printf "        -u|--username  Supply username\\n"
}

check(){ 
  command -v curl git jq >/dev/null || error "You'll curl, jq and git"
}

add_lines(){ printf "%s" "$1" | nl; }

while [ $# -ne 0 ]; do case "$1" in
  -h|--help)
    usage
    exit 0
    ;;
  -t|--http)
    [ -n "$mode" ] && error "Error in protocol"
    mode="http"
    ;;
  -s|--ssh)
    [ -n "$mode" ] && error "Error in protocol"
    mode="ssh"
    ;;
  -u|--username)
    [ -n "$user" ] && error "Username already defined"
    shift
    user="$1"
    ;;
  *)
    error "Unknown parameter $1"
    ;;
esac; shift; done

[ -z "$user" ] && error "No user specified"
mode=${mode:-http}
temp=$( mktemp )

curl -s "https://api.github.com/users/$user/repos" \
  | grep "clone_url\|description" \
  | tr -d "," \
  | cut -d "\"" -f 4- \
  | tr -d "\"" \
  | tee "$temp" \
  | wc -l \
  | xargs -I '{}' test "{}" -eq 0 \
  && rm -rf "$temp" \
  && error "User has no repos"

printf "%40s\\n" " " | tr " " "="
tac "$temp" \
  | awk 'NR%2==1 { printf $0 ": " }; NR%2==0 { print $0 }' \
  | cut -d "/" -f 5- \
  | tac \
  | sed "s/.git//" \
  | nl
printf "%40s\\n" " " | tr " " "="

nrepos=$( sed '1d;n;d' "$temp" | wc -l )
printf "Choose the repo: " && read -r choice
[ "$choice" -eq "$choice" ] 2>/dev/null || error "Not a number"
{ [ "$choice" -ge 1 ] && [ "$choice" -le "$nrepos" ]; } || error "Not in range"

choice=$(( choice+choice ))
repo=$( sed "${choice}q;d" "$temp" | cut -d "/" -f 5- )
printf "%s\\nIs this your choice? [y/N] " "$repo" && read -r l
{ [ "$l" = "y" ] || [ "$l" = "Y" ]; } 2>/dev/null || error "Abort"
[ "$mode" = "ssh" ]  && git clone "git@github.com:$user/$repo"
[ "$mode" = "http" ] && git clone "https://github.com/$user/$repo"
rm "$temp"
