#!/usr/bin/env sh

################################################################################
# Author		: Valerio Casalino
# Description		: This script shorten any github url with 
# 			  git.io/<something> (even that you can choose)
################################################################################

error() { printf "%s\\n" "$1"; exit 1; }

usage() {
	cat <<-EOF
	Usage: $( basename $0 ) https://github.com/<anything> (opt: -c custom)
	
	Outputs https://git.io/(<some-short-string> or <custom>)
	EOF
}

while [ "$#" -ne 0 ]; do case $1 in
  -c)
    [ -n "$code" ] && error "code already defined"
    shift
    code="$1"
    shift
    ;;
  *)
    [ -n "$url" ] && error "Url already defined"
    url="$1"
    shift
    ;;
esac done

args="url=$url"
[ -n "$code" ] && args="$args&code=$code"

curl -is https://git.io -d "$args" || error "No internet connection" \
  | grep "Location:" || error "Unprocessable Entity" \
  | cut -d' ' -f2 \
  | xargs -I '{}' printf "{}\\n" \
  || error "No internet connection or Invalid URL"
