#!/usr/bin/env sh

###############################################################################
# Script name		: pdfcompress.sh
# Author		: Valerio Casalino
# Description		: Compress your PDF
###############################################################################

SCRIPT_PATH="$( readlink -f "$0" )"
SCRIPT_NAME="${SCRIPT_PATH##*/}"

error() { printf "%s\\n" "$1" >&2 ; exit 1; }
usage() {
  printf "Script path: %s\\n" "$SCRIPT_PATH" \
    "Usage: %s [options] <arguments> inputfile.pdf\\n" "$SCRIPT_NAME" \
    "    -m|--mode     Choose the output quality [low, medium, high].\\n" \
    "    -i|--input    Choose the input file.\\n" \
    "    -o|--output   Choose the output file name.\\n" \
    "    -h|--help     Display this message.\\n\\n" \
    "Notes:\\n" \
    "    - If no mode is specified, the medium one will be selected.\\n" \
    "    - This script relies on GhostScript (gs), please install it \\n" \
    "      before you run the script: https://www.ghostscript.com/download\\n" \
    "      (it is included in many distro's repos by default)\\n" \
    "    - Might produce a larger output than the input...\\n"
}

compress() {
  gs \
    -q -dNOPAUSE -dBATCH -dSAFER \
    -sDEVICE=pdfwrite \
    -dCompatibilityLevel=1.5 \
    -dSimulateOverprint=true \
    -dPDFSETTINGS=/"$3" \
    -dEmbedAllFonts=true \
    -dSubsetFonts=true \
    -dColorImageDownsampleType=/Bicubic \
    -dColorImageResolution=150 \
    -dGrayImageDownsampleType=/Subsample \
    -dGrayImageResolution=150 \
    -dMonoImageDownsampleType=/Bicubic \
    -dMonoImageResolution=150 \
    -sOutputFile="$2" \
    "$1"
}

command -v gs > /dev/null || error "You need gs to run this script"

while [ "$#" -ne 0]; do case "$1" in
  -m|--mode)
    shift
    [ "$1" = "low" ] && mode="screen"
    [ "$1" = "medium" ] && mode="ebook"
    [ "$1" = "high" ] && mode="printer"
    [ -z "$mode" ] && error "$1 is not accepted"
    ;;
  -i|--input)
    shift
    [ ! -f "$1" ] && error "$1 is not a file!"
    inFile="$1"
    ;;
  -o|--output)
    shift
    outFile="$1"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage
    error "Unknown $1 argument"
    ;;
esac; shift; done

[ -z "$inFile" ] && error "You need at least the input file..."

compress "$inFile" "${outFile:-${inFile%.pdf}-compressed.pdf}" "${mode:-ebook}"
