#!/usr/bin/env sh
################################################################################
### Author:      Valerio Casalino                                            ###
### Description: Copy Useful regexs to clipboard                             ###
################################################################################

### Variables
_url="https://git.io/JfgTQ"
_cfgfile="${XDG_DATA_HOME:-$HOME/.local/share}/regex-list.txt"

### Functions
usage() {
  printf "Usage: regex-selector [OPTIONS] <args>\\n\\n"
  printf "    OPTIONS:\\n"
  printf "        -h, --help        Print Usage\\n"
  printf "        -r, --regenerate  Regenerate regex-list (use after custom\\n"
  printf "                          location argument)\\n"
  printf "        -c, --custom      Use the argument as config file\\n"
}

_generate_cfgfile() { [ -f "$_cfgfile" ] || wget --quiet "$_url" -O "$_cfgfile"; }

while [ "$#" -gt 0 ]; do case "$1" in
  -h|--help) usage && exit 0 ;;
  -r|--regenerate) rm "$_cfgfile"; _generate_cfgfile ;;
  -c|--custom) shift; _cfgfile="$1" ;; 
  *) ;;
esac; shift; done

[ ! -f "$_cfgfile" ] && _generate_cfgfile
command -v fzf xclip >/dev/null || { echo "Install fzf xclip"; exit 1; }

cat "$_cfgfile" | fzf | cut -d " " -f 2- | tee /dev/tty | xclip -selection c 
echo "Copied to clipboard"
