#!/usr/bin/env sh
# This script round-crops an image using ImageMagick

error() { printf "%s\n" "$1"; exit 1; }

[ $# -ne 1 ] && error "This script needs an Image to work!"
[ ! -f "$1" ] && error "The file doesn't exist"
command -v convert > /dev/null || error "Install imagemagick"

convert "$1" -alpha set \
    \( +clone -distort DePolar 0 -virtual-pixel HorizontalTile \
    -background None -distort Polar 0 \) \
    -compose Dst_In -composite -trim +repage "${1%.*}_rounded.png"
