#!/usr/bin/env sh

# Author: valerio Casalino
# This script downloads the NASA APOD: https://apod.nasa.gov/apod/astropix.html
# And the BING image of the day: https://www.bing.com/

SCRIPT="wallpaper-download"
DEFAULT_OUT="$HOME"
TEMP=$( mktemp )

# Checks
error() { printf "%s\\n" "$1"; rm "$TEMP"; exit 1; }
command -v curl > /dev/null || error "You need curl"
command -v jq > /dev/null || error "You need jq"

usage() {
  printf "Usage:\\n%s [-b|--bing:-n|--nasa:-h|--help] (optional)<output-dir>\\n" "$SCRIPT" 
}

bing() {
  curl -s "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=it-IT" -o "$TEMP"
  tmpvar=$( jq --raw-output '.title' < "$TEMP" | tr " " "-" )
  [ "$tmpvar" = "null" ] && tmpvar=$( date -I )
  title="${tmpvar}-bing.jpg"
  jq '.images[0].url' < "$TEMP" | xargs -I '{}' curl "https://bing.com{}" -o "$1/$title"
}

nasa() {
  curl -s "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY" -o "$TEMP"
  [ "$( jq --raw-output '.media_type' < "$TEMP" )" = "video" ] && error "No picture today"
  title="$( jq --raw-output '.title' < "$TEMP" | tr " " "-" )-nasa.jpg"
  jq '.hdurl' < "$TEMP" | xargs -I '{}' curl "{}" -o "$1/$title"
}

while [ $# -ne 0 ]; do case "$1" in
  -b|--bing) 
    [ -n "$USE" ] && error "Service already defined"
    USE="bing"
    shift
    ;;
  -n|--nasa)
    [ -n "$USE" ] && error "Service already defined"
    USE="nasa"
    shift
    ;;
  -h|--help) 
    usage 
    exit 0 
    ;;
  *)
    [ ! -d "$1" ] && error "Not valid output directory"
    OUT="$1"
    shift
    ;;
esac done

[ -z "$USE" ] && error "You need to choose nasa or bing (check usage)"

[ "$USE" = "nasa" ] && nasa "${OUT-${DEFAULT_OUT}}"
[ "$USE" = "bing" ] && bing "${OUT-${DEFAULT_OUT}}"
